CLS_HEAD:
  MAX_TEMP_LEN: 1000
  PE_DIM: 128
  PE_T: 1000
  POS_ENCODE_TYPE: default
  PROJ_ACT_TYPE: gelu
  PROJ_BOT_DIM: 64
  PROJ_HID_DIM: 256
  PROJ_HID_NLAYERS: 2
  PROJ_NORM_TYPE: batchnorm
  TAU: 0.1
  TEMP_ENCODER_TYPE: exchanger
  WITH_GDD_POS: False
DATASET:
  DATASET: PASTIS-R
  INPUT_DIM: [10]
  MODALITY: ['S2']
  NBINS: 16
  NUM_CLASSES: 19
  N_FOLD: 0
  PAD_VALUE: 0
  READER: PASTISReader
  ROOT: /home/cai-x/data/PASTIS-R
  TASK_TYPE: sem_seg
  TEMP_DROP_RATE: [[0.2, 0.4]]
  TEST_TILES: [{'year': 2017, 'country': 'france', 'tile': '31TCJ'}]
  THING_IDS: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]
  TRAIN_TILES: [{'year': 2017, 'country': 'austria', 'tile': '33UVP'}, {'year': 2017, 'country': 'denmark', 'tile': '32VNH'}, {'year': 2017, 'country': 'france', 'tile': '30TXT'}]
  Z_NORM: True
DEBUG:
  DEBUG: False
EXCHANGER:
  DROP_PATH_RATE: 0.1
  EMBED_DIMS: [128, 128]
  MLP_ACT: gelu
  MLP_NORM: batchnorm
  NUM_HEADS_LIST: [8, 8]
  NUM_TOKEN_LIST: [8, 8]
GPBLOCK:
  ACT_TYPE: gelu
  ADD_POS_TOKEN: True
  ATTN_DROP: 0.0
  DROP: 0.1
  DROP_PATH: 0.1
  EMBED_DIMS: 128
  FFN_RATIO: 4.0
  MIXER_CHANNEL_EXPANSION: 4.0
  MIXER_DEPTH: 1
  MIXER_TOKEN_EXPANSION: 0.5
  NORM_TYPE: layernorm
  NUM_GROUP_TOKENS: 8
  NUM_HEADS: 8
  QKV_BIAS: True
  UNTIED_POS_ENCODE: True
LOG_DIR: /home/cai-x/crop_cls/proj_001/Exchanger4SITS/log
LOSS:
  FOCAL: [0.25, 2.0]
  IGNORE_INDEX: -1
  SMOOTH_FACTOR: 0.0
  TYPE: crossentropy
LR:
  LR: 0.00002
  LR_FACTOR: 0.1
  LR_SCHEDULER: poly
  LR_STEP: [0.7, 0.9]
  WARMUP_FACTOR: 0.001
  WARMUP_ITERS_RATIO: 0.1
LTAE:
  ACT_TYPE: gelu
  DROPOUT: 0.1
  D_K: 8
  D_MODEL: 256
  MAX_TEMP_LEN: 1000
  MLP_DIMS: [128]
  NORM_TYPE: batchnorm
  N_HEAD: 16
  PE_T: 1000
  POS_ENC_TYPE: default
  WITH_GDD_POS: False
  WITH_POS_ENC: True
MASKFORMER:
  BACKBONE_TYPE: pvt
  CLS_WEIGHT: 2.0
  DEC_LAYERS: 6
  DICE_WEIGHT: 5.0
  DIM_FFD: 1024
  ENFORCE_INPUT_PROJECT: False
  HIDDEN_DIM: 256
  IMPORTANCE_SAMPLE_RATIO: 0.75
  MASK_DIM: 256
  MASK_WEIGHT: 5.0
  NUM_FEATURE_LEVELS: 3
  NUM_HEADS: 8
  NUM_POINTS: 128
  NUM_QUERIES: 19
  OBJECT_MASK_THRESHOLD: 0.7
  OVERLAP_THRESHOLD: 0.7
  OVERSAMPLE_RATIO: 3.0
  PIXEL_DECODER_TYPE: fpn
  PRE_NORM: False
MODEL:
  NAME: Segmentor
  PRETRAINED: /home/cai-x/crop_cls/proj_001/Exchanger4SITS/output/PASTIS-R_PixelSet/pastis_pixelset_exchanger_2stages_8tokens/Fold_0/final_state.pth
OPTIMIZER:
  MOMENTUM: 0.9
  TYPE: adamw
  WD: 0.05
OUTPUT_DIR: /home/cai-x/crop_cls/proj_001/Exchanger4SITS/output
PANOPTIC_SEGMENTOR:
  MAX_TEMP_LEN: 1000
  PE_DIM: 128
  PE_T: 1000
  POS_ENCODE_TYPE: default
  SPACE_ENCODER_TYPE: unet
  WITH_GDD_POS: False
PAPS_HEAD:
  BINARY_THRESHOLD: 0.4
  CENTER_LOSS_ALPHA: 2.0
  CENTER_LOSS_BETA: 4.0
  FOCAL_LOSS_GAMMA: 2.0
  LOSS_CENTER_WEIGHT: 1.0
  LOSS_CLASS_WEIGHT: 1.0
  LOSS_SHAPE_WEIGHT: 1.0
  LOSS_SIZE_WEIGHT: 1.0
  MASK_CONV: True
  MASK_THRESHOLD: 0.4
  MIN_CONFIDENCE: 0.2
  MIN_REMAIN: 0.5
  SHAPE_SIZE: 16
PRINT_FREQ: 5
PSE:
  ACT_TYPE: gelu
  MLP1_DIMS: [32, 64]
  MLP2_DIMS: [128]
  NORM_TYPE: batchnorm
PSELTAE:
  ACT_TYPE: gelu
  NORM_TYPE: batchnorm
  PROJ_ACT_TYPE: gelu
  PROJ_BOT_DIM: 64
  PROJ_HID_DIM: 256
  PROJ_HID_NLAYERS: 2
  PROJ_NORM_TYPE: batchnorm
  TAU: 0.1
PVT2:
  ATTN_DROP_RATE: 0.0
  DEPTHS: [2, 2, 2, 2]
  DROP_PATH_RATE: 0.1
  DROP_RATE: 0.1
  EMBED_DIMS: [64, 128, 320, 512]
  LINEAR: False
  MLP_RATIOS: [8, 8, 4, 4]
  NORM_TYPE: layernorm
  NUM_HEADS: [1, 2, 5, 8]
  QKV_BIAS: True
  SR_RATIOS: [8, 4, 2, 1]
SEGMENTOR:
  MAX_TEMP_LEN: 1000
  PE_DIM: 128
  PE_T: 1000
  POS_ENCODE_TYPE: default
  SPACE_ENCODER_TYPE: maskformer
  WITH_GDD_POS: False
SWIN:
  APE: False
  ATTN_DROP_RATE: 0.0
  DEPTHS: [2, 2, 6, 2]
  DROP_PATH_RATE: 0.2
  DROP_RATE: 0.1
  EMBED_DIM: 96
  FROZEN_STAGES: -1
  MLP_RATIO: 4.0
  NORM_LAYER_TYPE: layernorm
  NUM_HEADS: [3, 6, 12, 24]
  OUT_INDICES: [0, 1, 2, 3]
  PATCH_NORM: True
  PATCH_SIZE: 1
  PRETRAIN_IMG_SIZE: 224
  QKV_BIAS: True
  QK_SCALE: None
  USE_CHECKPOINT: False
  WINDOW_SIZE: 7
TEMP_SPAT_TRANSFORMER:
  ACT_TYPE: gelu
  ATTN_DROP: 0.0
  DROP: 0.1
  DROP_PATH: 0.1
  EMBED_DIMS: 128
  FFN_RATIO: 4.0
  NORM_TYPE: layernorm
  NUM_HEADS: 8
  NUM_TOKENS: 8
  QKV_BIAS: True
  SPATIAL_DEPTH: 2
  TEMPORAL_DEPTH: 4
  UNTIED_POS_ENCODE: True
  USE_SPACE_TRANSFORMER: True
TEST:
  BATCH_SIZE_PER_GPU: 1
  CROP_SIZE: (64, 64)
  MODEL_FILE: ./
  MULTI_CROP_TEST: False
  RETURN_ATTN: False
TRAIN:
  BATCH_SIZE_PER_GPU: 1
  BEGIN_EPOCH: 0
  CROP_SIZE: (64, 64)
  END_EPOCH: 100
  RANDOM_CROP: True
UNET:
  ACT_TYPE: gelu
  BASE_CHANNELS: 64
  DEC_DILATIONS: [1, 1, 1]
  DEC_NUM_CONVS: [2, 2, 2]
  DOWNSAMPLES: [True, True, True]
  ENC_DILATIONS: [1, 1, 1, 1]
  ENC_NUM_CONVS: [2, 2, 2, 2]
  NORM_TYPE: bn
  NUM_STAGES: 4
  STRIDES: [1, 1, 1, 1]
  UPSAMPLE_TYPE: interp
